/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MedButton {
        "ariaLabel": string;
        "disabled": boolean;
        "download": string | undefined;
        "href": string | undefined;
        "rel": string | undefined;
        "target": string | undefined;
        "type": 'submit' | 'reset' | 'button';
    }
    interface MedModal {
    }
}
declare global {
    interface HTMLMedButtonElement extends Components.MedButton, HTMLStencilElement {
    }
    var HTMLMedButtonElement: {
        prototype: HTMLMedButtonElement;
        new (): HTMLMedButtonElement;
    };
    interface HTMLMedModalElement extends Components.MedModal, HTMLStencilElement {
    }
    var HTMLMedModalElement: {
        prototype: HTMLMedModalElement;
        new (): HTMLMedModalElement;
    };
    interface HTMLElementTagNameMap {
        "med-button": HTMLMedButtonElement;
        "med-modal": HTMLMedModalElement;
    }
}
declare namespace LocalJSX {
    interface MedButton {
        "ariaLabel"?: string;
        "disabled"?: boolean;
        "download"?: string | undefined;
        "href"?: string | undefined;
        "onMedBlur"?: (event: CustomEvent<void>) => void;
        "onMedFocus"?: (event: CustomEvent<void>) => void;
        "rel"?: string | undefined;
        "target"?: string | undefined;
        "type"?: 'submit' | 'reset' | 'button';
    }
    interface MedModal {
    }
    interface IntrinsicElements {
        "med-button": MedButton;
        "med-modal": MedModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "med-button": LocalJSX.MedButton & JSXBase.HTMLAttributes<HTMLMedButtonElement>;
            "med-modal": LocalJSX.MedModal & JSXBase.HTMLAttributes<HTMLMedModalElement>;
        }
    }
}
